version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/WebLeoMp3Parser"
    update_schedule: "live"
    allowed_updates:
      - match:
          dependency_name: "LeoMp3Parser"
